# build an executable named my_current_processes from my_current_processes.c
all: my_current_processes.c
	gcc -g -Wall -o my_current_processes my_current_processes.c

clean:
	$(RM) my_current_processes
